### ISSUE TITLE
NoMethodError insert-demo-site-data

### ISSUE THREAD

**Issue by maxvlc** [denny/ShinyCMS-ruby#287]
## Description
I'd like to start contributing to this project, but as the Readme says, I get an `rails aborted` error when running this command at final part of the Database section.

```
➜  ShinyCMS-ruby git:(master) tools/insert-demo-site-data
This will wipe your database; are you sure? (y/n) y
.
.
.
rails aborted!
NoMethodError: undefined method `page_templates_path' for nil:NilClass
/home/max/web/ShinyCMS-ruby/app/models/page_template.rb:49:in `template_dir'
/home/max/web/ShinyCMS-ruby/app/models/page_template.rb:54:in `available_templates'
/home/max/web/ShinyCMS-ruby/app/models/page_template.rb:64:in `<class:PageTemplate>'
/home/max/web/ShinyCMS-ruby/app/models/page_template.rb:4:in `<main>'
/home/max/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/max/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_
.
.
.
/home/max/.rvm/gems/ruby-2.6.6/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/max/.rvm/gems/ruby-2.6.6/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
bin/rails:9:in `<main>'
Tasks: TOP => db:fixtures:load
(See full trace by running task with --trace)

```

**Comment by denny** [comment]
Thanks for the report; can you grab the latest master and let me know if that's fixed it for you?

**Comment by maxvlc** [comment]
Hi @denny The process is still failing, I leave you below all the console error.

```
➜  ShinyCMS-ruby git:(master) tools/insert-demo-site-data
This will wipe your database; are you sure? (y/n) y
rails aborted!
NoMethodError: undefined method `page_templates_path' for nil:NilClass
/home/max/web/ShinyCMS-ruby/app/models/page_template.rb:49:in `template_dir'
/home/max/web/ShinyCMS-ruby/app/models/page_template.rb:54:in `available_templates'
/home/max/web/ShinyCMS-ruby/app/models/page_template.rb:64:in `<class:PageTemplate>'
/home/max/web/ShinyCMS-ruby/app/models/page_template.rb:4:in `<main>'
/home/max/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/max/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/max/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/max/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/max/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/max/.rvm/gems/ruby-2.6.6/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:16:in `require'
/home/max/.rvm/gems/ruby-2.6.6/gems/activesupport-6.0.2.2/lib/active_support/inflector/methods.rb:282:in `const_get'
/home/max/.rvm/gems/ruby-2.6.6/gems/activesupport-6.0.2.2/lib/active_support/inflector/methods.rb:282:in `block in constantize'
/home/max/.rvm/gems/ruby-2.6.6/gems/activesupport-6.0.2.2/lib/active_support/inflector/methods.rb:280:in `each'
/home/max/.rvm/gems/ruby-2.6.6/gems/activesupport-6.0.2.2/lib/active_support/inflector/methods.rb:280:in `inject'
/home/max/.rvm/gems/ruby-2.6.6/gems/activesupport-6.0.2.2/lib/active_support/inflector/methods.rb:280:in `constantize'
/home/max/.rvm/gems/ruby-2.6.6/gems/activesupport-6.0.2.2/lib/active_support/inflector/methods.rb:325:in `safe_constantize'
/home/max/.rvm/gems/ruby-2.6.6/gems/activesupport-6.0.2.2/lib/active_support/core_ext/string/inflections.rb:79:in `safe_constantize'
/home/max/.rvm/gems/ruby-2.6.6/gems/activerecord-6.0.2.2/lib/active_record/fixtures.rb:461:in `block in []'
/home/max/.rvm/gems/ruby-2.6.6/gems/activerecord-6.0.2.2/lib/active_record/fixtures.rb:460:in `fetch'
/home/max/.rvm/gems/ruby-2.6.6/gems/activerecord-6.0.2.2/lib/active_record/fixtures.rb:460:in `[]'
/home/max/.rvm/gems/ruby-2.6.6/gems/activerecord-6.0.2.2/lib/active_record/fixtures.rb:577:in `block in read_and_insert'
/home/max/.rvm/gems/ruby-2.6.6/gems/activerecord-6.0.2.2/lib/active_record/fixtures.rb:576:in `map'
/home/max/.rvm/gems/ruby-2.6.6/gems/activerecord-6.0.2.2/lib/active_record/fixtures.rb:576:in `read_and_insert'
/home/max/.rvm/gems/ruby-2.6.6/gems/activerecord-6.0.2.2/lib/active_record/fixtures.rb:546:in `create_fixtures'
/home/max/.rvm/gems/ruby-2.6.6/gems/activerecord-6.0.2.2/lib/active_record/railties/databases.rake:359:in `block (3 levels) in <main>'
/home/max/.rvm/gems/ruby-2.6.6/gems/railties-6.0.2.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/max/.rvm/gems/ruby-2.6.6/gems/railties-6.0.2.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/max/.rvm/gems/ruby-2.6.6/gems/railties-6.0.2.2/lib/rails/command.rb:48:in `invoke'
/home/max/.rvm/gems/ruby-2.6.6/gems/railties-6.0.2.2/lib/rails/commands.rb:18:in `<main>'
/home/max/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/max/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/max/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/max/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/max/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/max/.rvm/gems/ruby-2.6.6/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
/home/max/.rvm/gems/ruby-2.6.6/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/max/.rvm/gems/ruby-2.6.6/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
bin/rails:9:in `<main>'
Tasks: TOP => db:fixtures:load
(See full trace by running task with --trace)

```

**Comment by denny** [comment]
Hrm, okay. Sorry about that - adding that ENV var worked on my system - I'll dig a bit more later.

**Comment by denny** [comment]
@maxvlc I got the ENV var name wrong! :facepalm:  Try it again now please?

**Comment by maxvlc** [comment]
Now the process end successfully, but on starting the server I got a new related error with the template.

i will take a look over it and I let you know...

```
  ↳ app/models/page_section.rb:104:in `default_section'
  Page Load (0.3ms)  SELECT "pages".* FROM "pages" WHERE "pages"."section_id" IS NULL AND "pages"."hidden" = $1 ORDER BY "pages"."sort_order" ASC  [["hidden", false]]
  ↳ app/models/page.rb:97:in `min'
  CACHE Setting Load (0.0ms)  SELECT "settings".* FROM "settings" WHERE "settings"."name" = $1 LIMIT $2  [["name", "theme_name"], ["LIMIT", 1]]
  ↳ app/models/setting.rb:49:in `get'
  CACHE SettingValue Load (0.0ms)  SELECT "setting_values".* FROM "setting_values" WHERE "setting_values"."setting_id" = $1 LIMIT $2  [["setting_id", 10], ["LIMIT", 11]]
  ↳ app/models/setting.rb:22:in `setting_value'
  CACHE SettingValue Load (0.0ms)  SELECT "setting_values".* FROM "setting_values" WHERE "setting_values"."setting_id" = $1 AND "setting_values"."user_id" IS NULL LIMIT $2  [["setting_id", 10], ["LIMIT", 1]]
  ↳ app/models/setting.rb:23:in `setting_value'
Completed 500 Internal Server Error in 313ms (ActiveRecord: 42.9ms | Allocations: 248057)

 
NoMethodError (undefined method `page_templates_path' for nil:NilClass):
  
app/models/page_template.rb:49:in `template_dir'
app/models/page_template.rb:54:in `available_templates'
app/models/page_template.rb:64:in `<class:PageTemplate>'
app/models/page_template.rb:4:in `<main>'
app/controllers/pages_controller.rb:78:in `show_page'
app/controllers/pages_controller.rb:19:in `index'
```
