### ISSUE TITLE
rails shiny:demo:load doesn't work

### ISSUE THREAD

**Issue by 007lva** [denny/ShinyCMS-ruby#321]
Hi, I've got this error after to fill the email for the admin account:

```
rails aborted!
NoMethodError: undefined method `page_templates_path' for nil:NilClass
/home/lvargas/projects/ShinyCMS-ruby/app/models/page_template.rb:49:in `template_dir'
/home/lvargas/projects/ShinyCMS-ruby/app/models/page_template.rb:54:in `available_templates'
/home/lvargas/projects/ShinyCMS-ruby/app/models/page_template.rb:64:in `<class:PageTemplate>'
/home/lvargas/projects/ShinyCMS-ruby/app/models/page_template.rb:4:in `<main>'
/home/lvargas/.gem/ruby/2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/lvargas/.gem/ruby/2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/lvargas/.gem/ruby/2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/lvargas/.gem/ruby/2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/lvargas/.gem/ruby/2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/lvargas/.gem/ruby/2.7.1/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:16:in `require'
/home/lvargas/projects/ShinyCMS-ruby/lib/tasks/demo.rake:27:in `block (3 levels) in <main>'
/home/lvargas/.gem/ruby/2.7.1/gems/railties-6.0.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/lvargas/.gem/ruby/2.7.1/gems/railties-6.0.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/lvargas/.gem/ruby/2.7.1/gems/railties-6.0.3/lib/rails/command.rb:48:in `invoke'
/home/lvargas/.gem/ruby/2.7.1/gems/railties-6.0.3/lib/rails/commands.rb:18:in `<main>'
/home/lvargas/.gem/ruby/2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/lvargas/.gem/ruby/2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/lvargas/.gem/ruby/2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/lvargas/.gem/ruby/2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/lvargas/.gem/ruby/2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/lvargas/.gem/ruby/2.7.1/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `block in require'
/home/lvargas/.gem/ruby/2.7.1/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/lvargas/.gem/ruby/2.7.1/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
bin/rails:9:in `<main>'
Tasks: TOP => shiny:demo:load
(See full trace by running task with --trace)
```

**Comment by denny** [comment]
Oops, pretty sure that's a regression of a bug I fixed on the previous demo-data script.

Can you try this for me please? `SHINYCMS_THEME=halcyonic rails shiny:demo:load`

**Comment by 007lva** [comment]
It works for the rake task =), but once I boot the app I get the same error:

![Screenshot_2020-05-18_00-06-26](https://user-images.githubusercontent.com/1860816/82161246-6f20e100-989b-11ea-93ce-4e673e24ebbd.png)

I see that this can be fixed in the same way:

`SHINYCMS_THEME=halcyonic rails s`

**Comment by denny** [comment]
I'll try to get this fixed tomorrow; for now you should be able to set that ENV var in your .env.development.local file to save you having to type it in every time :)

**Comment by eliotsykes** [comment]
This appears to be fixed in latest master.

These are the steps I ran through and I didn't get errors on the rake task nor on browsing the site:

```sh
git clone https://github.com/denny/ShinyCMS-ruby.git
cd ShinyCMS-ruby
cp docs/env.sample .env.development.local # then edited file
bundle install
yarn install  
rails db:setup
rails shiny:demo:load
rails s
```

**Comment by denny** [comment]
> ```shell
> cp docs/env.sample .env.development.local # then edited file
> ```

I suspect this is where you escaped the explosions; SHINYCMS_THEME is set on line 22 of that file.

**Comment by denny** [comment]
@007lva Sorry this has taken so long, but I think I've tracked this down today, and fixed it in master. You shouldn't need to set the theme name yourself at any point now - it gets set by the rake task when you load the demo data, and then picked up from the database after that.

Let me know if it works for you! :slightly_smiling_face:

**Comment by 007lva** [comment]
Thanks @denny , now it's working!
